/*Creación de la tabla con los cursos*/
CREATE TABLE CURSO(
ID int auto_increment PRIMARY KEY,
NOMBRE varchar(15) NOT NULL);

/*Creación de la tabla de alumnos*/
CREATE TABLE ALUMNO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(20) NOT NULL,
  PRIMERAPELLIDO VARCHAR(45) NOT NULL,
  SEGUNDOAPELLIDO VARCHAR(45) NULL,
  CURSO INT NULL,
  CONSTRAINT fk_alumno_curso FOREIGN KEY (CURSO) REFERENCES CURSO(ID));